branches:
  only:
  - master
script:
- docker build --target production --tag moot-app .
- docker image tag moot-app "${DOCKER_USERNAME}/moot-app:latest"
- docker image tag moot-app "${DOCKER_USERNAME}/moot-app:${TRAVIS_COMMIT}"
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "${DOCKER_USERNAME}/moot-app:latest"
- docker push "${DOCKER_USERNAME}/moot-app:${TRAVIS_COMMIT}"
- docker tag "${DOCKER_USERNAME}/moot-app:latest" registry.heroku.com/moot-bookings/web
- echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
- docker push registry.heroku.com/moot-bookings/web
- heroku container:release web -a moot-bookings
env:
  global:
  - DOCKER_USERNAME=charliecumbermoot
  - secure: fXV69Xv/a3Kxx77HKZqqDETLjkD2E5ASnlskVUfOX4rEf3rBg09/b+FYTbtHG3Tm/upKUSoAWzCvPPjUjWj15IgN59LPoEF1MiCK+CllFmdCDyCHdRXR6Ld4z6mJmorANkvZvufx42imfnUhe6du2TipcVbrddYhBRzNDgjy9P9rwhuNwbPP+ykhSz+p6kNSOzZWNpMQGrCdj3tNiVOme0jPUOOxee+5fBt2SsxX7UXYCO29KDoaLC45Y+YHrlAbFb1qanURvgEnFkt2STYQMq3SajiFVSOS0K1fdcEbRu90vbCgifnnCBiU5/oWZc8dMvKMvGf85zHGe48nSx08JCUbdsYFAKaufsKr8sRmSAXyJhL0T1zt90FegdcMCA44imPP8DF2JKACPM0/CHIhcou7rahdU292gjAABP1CM+EfGk40BxckoHzF4NiLirARZwrYEr1SlWtbC6bDv3nikBArRfH+qQ7CFPDJwu9yplxepmB23ySVvwSYgpmgtKkvBCzqqG6uUgzlCcpV75qimxg1SDg3eNkG3+UtwbHrNhevZv54530ZOsO/9OJPvL6yXjkiNt3bBEDimak8UrbVFEXShX4PFrdrAzNSPCYAuj1hifABR+ByfMBxDUQ4nJH3NdJCkz4jb/sWEkkgI6et2jY8oYYRavo9Brtg6ZHhL7k=
  - secure: liVq7VsRGbs4599ia1Ub5l0LOT90pCARSGWW38g5gRUM9oMAxlOAzjzYMDXRPUcVdL6JtERiJRAT3obxtE0YzvQdJKX+Mw0DE9BQCyLKdUNT/sN390Treb4Qu+1WnyQv2JlPVYS6LRrMJ5Pv49KP0DstZecMxB8UKDqj7EYfeaIghcclOUeGpwj/7/2OjVynZHOUhEBnd9PAqxqAOl72LeKS20BD4iQVdUhE7mR3ajwykk60BUWM3Q9rLptszhgyZyRNipW16ydqZqtLDN+ycGcpIy8+3T+1kAUmZ8SFvBLooQ8UR5pcv5AGqkr+SjInsIbfkKzRB7fZTGXU6ludN/QAgxyy3SFu9DUpQ/V+pa9XRUnR4jdc722YdAAuX2VgudDMbJgMQLNxgB5RXvJjUl/NTE/lgCng0G7j484qsr64BXDe0X9sxfkuEA/dvh+qDGWoRYbmkziji+KMC2EilHzyLzoo6ZlYP/1AJLV2ku4mi2Rk8vF32lyiFtf068nvXFoCnrqo+9sQc+fAHikn/QPuo8jCbU+2PCsYcPNinezyn4pYaFmyinAddXLG0ZGQFDXBSneL7Iab6t1bQk/tE744O06FHbYuAc6cnodFHB23V8P5k+0019aUuKwSF0JrTYvKpgSXeemwEAGQ0yGKMUDUoiWktYgCBXNWaUEbBBY=
