version: '3.8'
services: 
    moot-app:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        image: moot-app:prod
        ports:
            - "5000:5000"
        env_file: .env
