version: '3.8'
services: 
    moot-app:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        image: moot-app:dev
        ports: 
            - "5000:5000"
        env_file: .env
        volumes:
          - type: bind
            source: ./moot_app/
            target: /app/moot_app